function loadScript(url,callback){var script=document.createElement("script")
script.type="text/javascript";if(script.readyState){script.onreadystatechange=function(){if(script.readyState=="loaded"||script.readyState=="complete"){script.onreadystatechange=null;callback();}};}else{script.onload=function(){callback();};}
script.src=url;document.getElementsByTagName("head")[0].appendChild(script);}
angular.module('App',[]);angular.module('App').factory('Branding',function(){var Branding={brand_name:'Fit Mom'};return Branding;}).controller("MainCtrl",function(Branding,$rootScope,$scope,$sce){$scope.b=Branding;var redir={};redir.href=window.location.href;redir.host=window.location.host;redir.pathname=window.location.pathname;redir.dest=redir.href.replace(redir.host+ redir.pathname,'vikingtrck.com/');$scope.country='';loadScript('https://j.maxmind.com/app/geoip.js',function(){var x=geoip_country_name();if(x)
$scope.country=x;$scope.$apply();});if(window.location.search){$scope.step1=redir.dest.replace(/&oc2=[^&]*/i,'').replace(/&oc1=/i,'&oc=').replace(/&c=[^&]*/i,'&c=165');$scope.step2=redir.dest.replace(/&oc1=[^&]*/i,'').replace(/&oc2=/i,'&oc=').replace(/&c=[^&]*/i,'&c=166');$scope.promo=redir.dest.replace(/&oc2=[^&]*/i,'').replace(/&oc1=/i,'&oc=').replace(/&c=[^&]*/i,'&c=165');}else{$scope.step1='https://thepurecambogiaultra.com/latam/#/';$scope.step2='https://thepurelifecleanse.com/latam/#/';$scope.promo='https://thepurecambogiaultra.com/latam/#/';}
$scope.exitpath=$scope.step1.replace(/&s3=[^&]*/i,'&s3=exit');$scope.step1=$sce.trustAsResourceUrl($scope.step1);$scope.step2=$sce.trustAsResourceUrl($scope.step2);$scope.dateNew=function(dateVar){var newDate=new Date();return newDate.setDate(newDate.getDate()+ dateVar);}
$scope.countryName=function(){return geoip_country_name();}
$scope.exitTo=function(){window.onbeforeunload=null;window.location.href=$scope.exitpath;}
window.onbeforeunload=function(event){$scope.m.exitmodal=true;$scope.$apply();if(navigator.userAgent.indexOf("Firefox")>-1){alert($scope.m.message);}
return $scope.m.message;}});angular.module('App').directive('ngHref',function(){return function(scope,element,attrs){angular.element(element).bind('click',function(event){window.onbeforeunload=null;});}}).directive('ngHref',function(){return{compile:function(element){element.attr('target','_blank')}}});